Tests: less intermediate files

diff --git a/test/hash/Makefile b/test/hash/Makefile
--- a/test/hash/Makefile
+++ b/test/hash/Makefile
@@ -22,11 +22,8 @@ asm: bin/test_xmssmt-sha2_20_2_256.s
 test: bin/test_xmssmt-sha2_20_2_256
 run: bin/test_xmssmt-sha2_20_2_256.out
 
-checkCT: test_hash.jazz
-	echo "from XMSS require \"params/params-xmssmt-sha2_20_2_256.jinc\"" > tmp
-	cat $< >> tmp
-	$(JASMINPATH) $(JAZZCT) $(JAZZCTFLAGS) tmp >/dev/null 2>&1 || { rm tmp ; echo "Jasmin CT check failed"; exit 1; }
-	rm tmp
+checkCT: test_hash-sha2_20_2_256.jazz test_hash.jazz
+	$(JASMINPATH) $(JAZZCT) $(JAZZCTFLAGS) $< >/dev/null 2>&1 || { echo "Jasmin CT check failed"; exit 1; }
 
 # --------------------------------------------------------------------------------------------------
 
@@ -37,11 +34,8 @@ TEST_FLAGS := -DTEST_PRF -DTEST_PRF_KEYGEN -DTEST_THASH_F -DTEST_THASH_H -DTEST_
 # --------------------------------------------------------------------------------------------------
 
 .PRECIOUS: bin/test_xmssmt-sha2_20_2_256.s
-bin/test_xmssmt-sha2_20_2_256.s: test_hash.jazz | bin/
-	echo "from XMSS require \"params/params-xmssmt-sha2_20_2_256.jinc\"" > tmp
-	cat $< >> tmp
-	$(JASMIN) $(JINCLUDE) $(JFLAGS) -o $@ tmp || rm tmp # remove the file even when compilation fails
-	rm tmp
+bin/test_xmssmt-sha2_20_2_256.s: test_hash-sha2_20_2_256.jazz test_hash.jazz | bin/
+	$(JASMIN) $(JINCLUDE) $(JFLAGS) -o $@ $<
 
 
 bin/test_xmssmt-sha2_20_2_256: bin/test_xmssmt-sha2_20_2_256.s
