Tests: less intermediate files

diff --git a/test/treehash/Makefile b/test/treehash/Makefile
--- a/test/treehash/Makefile
+++ b/test/treehash/Makefile
@@ -21,11 +21,8 @@ asm: bin/test_xmssmt-sha2_20_2_256.s
 test: bin/test_xmssmt-sha2_20_2_256
 run: bin/test_xmssmt-sha2_20_2_256.out
 
-checkCT: test_treehash.jazz
-	echo "from XMSS require \"params/params-xmssmt-sha2_20_2_256.jinc\"" > tmp
-	cat $< >> tmp
-	$(JASMINPATH) $(JAZZCT) $(JAZZCTFLAGS) tmp >/dev/null 2>&1 || { rm tmp ; echo "Jasmin CT check failed"; exit 1; }
-	rm tmp
+checkCT: test_treehash-sha2_20_2_256.jazz test_treehash.jazz
+	$(JASMINPATH) $(JAZZCT) $(JAZZCTFLAGS) $< >/dev/null 2>&1 || { echo "Jasmin CT check failed"; exit 1; }
 
 # --------------------------------------------------------------------------------------------------
 
@@ -36,11 +33,8 @@ TEST_FLAGS := -DTEST_TREEHASH -DTEST_AUTH_PATH -DTEST_TREESIG -DDEBUG
 # --------------------------------------------------------------------------------------------------
 
 .PRECIOUS: bin/test_xmssmt-sha2_20_2_256.s
-bin/test_xmssmt-sha2_20_2_256.s: test_treehash.jazz | bin/
-	echo "from XMSS require \"params/params-xmssmt-sha2_20_2_256.jinc\"" > tmp
-	cat $< >> tmp
-	$(JASMIN) $(JINCLUDE) $(JFLAGS) -o $@ tmp # || rm tmp # remove the file even when compilation fails
-	# rm tmp
+bin/test_xmssmt-sha2_20_2_256.s: test_treehash-sha2_20_2_256.jazz test_treehash.jazz | bin/
+	$(JASMIN) $(JINCLUDE) $(JFLAGS) -o $@ $<
 
 bin/test_xmssmt-sha2_20_2_256: bin/test_xmssmt-sha2_20_2_256.s
 	$(CC) $(CFLAGS) -o $@ -I../common -I../ -I ../new_treehash/ -DIMPL=XMSSMT-SHA2_20/2_256 $(TEST_FLAGS) \
